import type { IncomingMessage, ServerResponse } from "node:http";
import { query } from "../core/database.js";

const json=(res:ServerResponse,status:number,body:unknown)=>{res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(body));};
async function body(req:IncomingMessage):Promise<Record<string,unknown>>{const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(Buffer.from(chunk));if(!chunks.length)return{};return JSON.parse(Buffer.concat(chunks).toString("utf8"));}
function tenant(req:IncomingMessage){const id=req.headers["x-petra-company-id"];if(process.env.PETRA_ENVIRONMENT!=="development"||typeof id!=="string"||!/^[0-9a-f-]{36}$/i.test(id))throw Object.assign(new Error("Contexto da empresa não autenticado."),{status:401,code:"TENANT_CONTEXT_REQUIRED"});return id;}
function role(req:IncomingMessage,allowed:string[]){const value=req.headers["x-petra-role"];if(typeof value!=="string"||!allowed.includes(value))throw Object.assign(new Error("Permissão insuficiente."),{status:403,code:"FORBIDDEN"});}
export async function handleOperationsApi(req:IncomingMessage,res:ServerResponse,path:string):Promise<boolean>{
 if(!path.startsWith("/api/v1/operations"))return false;
 try{const companyId=tenant(req);const parts=path.replace(/^\/api\/v1\/operations\/?/,"").split("/").filter(Boolean);const resource=parts[0]??"dashboard";const id=parts[1];
  if(resource==="dashboard"&&req.method==="GET"){const[d,p,late,pay]=await Promise.all([query<{count:string}>("select count(*)::text count from petra.demands where company_id=$1 and status not in ('completed','cancelled')",[companyId]),query<{count:string}>("select count(*)::text count from petra.demands where company_id=$1 and status='pending'",[companyId]),query<{count:string}>("select count(*)::text count from petra.demands where company_id=$1 and status not in ('completed','cancelled') and due_at<now()",[companyId]),query<{amount:string,count:string}>("select coalesce(sum(amount),0)::text amount,count(*)::text count from petra.payment_events where company_id=$1 and status='processed'",[companyId])]);json(res,200,{ok:true,data:{openDemands:Number(d[0]?.count??0),pendingDemands:Number(p[0]?.count??0),overdueDemands:Number(late[0]?.count??0),recognizedPayments:Number(pay[0]?.count??0),recognizedAmount:Number(pay[0]?.amount??0)}});return true;}
  if(resource==="demands"&&!id&&req.method==="GET"){json(res,200,{ok:true,data:await query("select d.*,u.full_name responsible_name,case when d.status not in ('completed','cancelled') and d.due_at<now() then true else false end overdue from petra.demands d left join petra.users u on u.id=d.responsible_user_id and u.company_id=d.company_id where d.company_id=$1 order by d.due_at nulls last,d.priority desc,d.created_at desc",[companyId])});return true;}
  if(resource==="demands"&&!id&&req.method==="POST"){role(req,["admin","commercial","technical","production","installation"]);const b=await body(req);if(typeof b.title!=="string"||typeof b.task_type!=="string"){json(res,400,{ok:false,error:{code:"DEMAND_FIELDS_REQUIRED",message:"title e task_type são obrigatórios."}});return true;}const rows=await query("insert into petra.demands(company_id,order_id,quote_id,title,task_type,responsible_user_id,status,priority,starts_at,due_at,estimated_minutes,metadata) values($1,$2,$3,$4,$5,$6,coalesce($7,'pending'),coalesce($8,'normal'),$9,$10,$11,$12) returning *",[companyId,b.order_id??null,b.quote_id??null,b.title,b.task_type,b.responsible_user_id??null,b.status??null,b.priority??null,b.starts_at??null,b.due_at??null,Number(b.estimated_minutes??0),b.metadata??{}]);json(res,201,{ok:true,data:rows[0]});return true;}
  if(resource==="demands"&&id&&req.method==="PATCH"){role(req,["admin","commercial","technical","production","installation"]);const b=await body(req);const rows=await query("update petra.demands set responsible_user_id=coalesce($1,responsible_user_id),status=coalesce($2,status),priority=coalesce($3,priority),starts_at=coalesce($4,starts_at),due_at=coalesce($5,due_at),estimated_minutes=coalesce($6,estimated_minutes),actual_minutes=coalesce($7,actual_minutes),completed_at=case when $2='completed' then coalesce(completed_at,now()) else completed_at end,metadata=coalesce($8,metadata) where id=$9 and company_id=$10 returning *",[b.responsible_user_id??null,b.status??null,b.priority??null,b.starts_at??null,b.due_at??null,b.estimated_minutes==null?null:Number(b.estimated_minutes),b.actual_minutes==null?null:Number(b.actual_minutes),b.metadata??null,id,companyId]);if(!rows.length){json(res,404,{ok:false,error:{code:"DEMAND_NOT_FOUND",message:"Demanda não encontrada."}});return true;}json(res,200,{ok:true,data:rows[0]});return true;}
  if(resource==="productivity"&&req.method==="GET"){json(res,200,{ok:true,data:await query("select * from petra.productivity_by_user where company_id=$1 order by completion_rate desc,on_time_rate desc,full_name",[companyId])});return true;}
  if(resource==="payments"&&parts[1]==="reconcile"&&req.method==="POST"){role(req,["admin","finance","commercial"]);const b=await body(req);if(typeof b.external_id!=="string"||typeof b.order_id!=="string"||typeof b.amount!=="number"){json(res,400,{ok:false,error:{code:"PAYMENT_FIELDS_REQUIRED",message:"external_id, order_id e amount são obrigatórios."}});return true;}const rows=await query("select petra.reconcile_payment($1,$2,$3,$4,$5,$6,$7,$8) result",[companyId,b.external_id,b.amount,b.order_id,b.payment_method??null,b.occurred_at??new Date().toISOString(),b.source??"gateway",b.payload??{}]);json(res,200,{ok:true,data:rows[0]?.result??null});return true;}
  if(resource==="payments"&&req.method==="GET"){json(res,200,{ok:true,data:await query("select pe.*,o.number order_number,c.name customer_name from petra.payment_events pe left join petra.orders o on o.id=pe.order_id and o.company_id=pe.company_id left join petra.customers c on c.id=o.customer_id and c.company_id=o.company_id where pe.company_id=$1 order by pe.occurred_at desc",[companyId])});return true;}
  json(res,404,{ok:false,error:{code:"NOT_FOUND",message:"Endpoint operacional não encontrado."}});return true;
 }catch(error){const e=error as Error&{status?:number;code?:string};json(res,e.status??500,{ok:false,error:{code:e.code??"INTERNAL_ERROR",message:e.message}});return true;}}
