import { randomUUID } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";
import { databaseConfigured, query } from "../core/database.js";

const json=(res:ServerResponse,status:number,body:unknown)=>{res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(body));};
async function body(req:IncomingMessage):Promise<Record<string,unknown>>{const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(Buffer.from(chunk));if(!chunks.length)return{};try{return JSON.parse(Buffer.concat(chunks).toString("utf8"));}catch{throw Object.assign(new Error("JSON inválido."),{status:400,code:"INVALID_JSON"});}}
function tenant(req:IncomingMessage):string{const id=req.headers["x-petra-company-id"];if(process.env.PETRA_ENVIRONMENT!=="development"||typeof id!=="string"||!/^[0-9a-f-]{36}$/i.test(id))throw Object.assign(new Error("Contexto da empresa não autenticado."),{status:401,code:"TENANT_CONTEXT_REQUIRED"});return id;}
function role(req:IncomingMessage,allowed:string[]){const value=req.headers["x-petra-role"];if(typeof value!=="string"||!allowed.includes(value))throw Object.assign(new Error("Permissão insuficiente."),{status:403,code:"FORBIDDEN"});}

const CORE_MODULES=["dashboard","commercial","quotes","orders","measurement","technical","production","finishing","logistics","installation","finance","inventory","customers","documents","reports","marketing","automations","assistant"];

async function ensureModules(companyId:string){
 await query("select petra.ensure_company_modules($1)",[companyId]);
}

async function processOrderCreationJobs(companyId:string){
 const jobs=await query<{id:string,payload:any}>("select id,payload from petra.automation_jobs where company_id=$1 and target='order.create' and status='pending' and run_at<=now() order by created_at for update",[companyId]);
 for(const job of jobs){
  try{
   const p=job.payload??{};
   const existing=await query<{id:string}>("select id from petra.orders where company_id=$1 and quote_id=$2 limit 1",[companyId,p.quote_id]);
   if(!existing.length){
    const count=await query<{n:string}>("select count(*)::text n from petra.orders where company_id=$1",[companyId]);
    const number=`PED-${String(Number(count[0]?.n??0)+1).padStart(6,"0")}`;
    await query("insert into petra.orders(company_id,customer_id,work_id,quote_id,number,status,payment_terms,total,notes) values($1,$2,$3,$4,$5,'new',$6,$7,$8)",[companyId,p.customer_id??null,p.work_id??null,p.quote_id,number,p.payment_terms??null,Number(p.total??0),"Gerado automaticamente a partir do orçamento aprovado"]);
   }
   await query("update petra.automation_jobs set status='completed',completed_at=now(),attempts=attempts+1 where id=$1",[job.id]);
  }catch(error){await query("update petra.automation_jobs set status='failed',last_error=$1,attempts=attempts+1 where id=$2",[error instanceof Error?error.message:"Falha na automação",job.id]);}
 }
}

export async function handleApi(req:IncomingMessage,res:ServerResponse,path:string):Promise<boolean>{
 if(!path.startsWith("/api/v1/"))return false;
 try{
  const parts=path.replace(/^\/api\/v1\//,"").split("/").filter(Boolean);const resource=parts[0];const id=parts[1];
  if(resource==="setup"&&parts[1]==="status"&&req.method==="GET"){
   let databaseReachable=false;let migrationsCurrent=false;let migrationError:string|undefined;
   if(databaseConfigured())try{await query("select 1");databaseReachable=true;const rows=await query<{version:string}>("select version from petra.schema_migrations order by version desc");migrationsCurrent=rows.some(r=>r.version==="004_automation_engine"||r.version==="005_module_configuration");}catch(error){migrationError=error instanceof Error?error.message:"Falha ao verificar banco de dados.";}
   json(res,200,{ok:true,data:{ready:databaseReachable&&migrationsCurrent,checks:{databaseConfigured:databaseConfigured(),databaseReachable,migrationsCurrent},required:["PETRA_DATABASE_URL","migrations 001-005"],optional:["MOTOR_PETRA_URL","MOTOR_PETRA_SERVICE_TOKEN","PETRA_AUTOMATION_WORKER_ENABLED"],error:migrationError??null}});return true;
  }
  const companyId=tenant(req);await ensureModules(companyId);
  if(resource==="setup"&&parts[1]==="modules"&&req.method==="GET"){
   const rows=await query("select module_key,enabled,configured,settings from petra.company_modules where company_id=$1 order by module_key",[companyId]);
   const present=new Set(rows.map((r:any)=>r.module_key));
   for(const moduleKey of CORE_MODULES)if(!present.has(moduleKey))rows.push({module_key:moduleKey,enabled:true,configured:true,settings:{}});
   json(res,200,{ok:true,data:{onboardingCompleted:true,modules:rows}});return true;
  }
  if(resource==="setup"&&parts[1]==="modules"&&req.method==="PATCH"){
   role(req,["admin"]);const b=await body(req);if(typeof b.module_key!=="string"||!CORE_MODULES.includes(b.module_key)){json(res,400,{ok:false,error:{code:"MODULE_INVALID",message:"Módulo inválido."}});return true;}
   const rows=await query("update petra.company_modules set enabled=coalesce($1,enabled),configured=true,settings=coalesce($2,settings) where company_id=$3 and module_key=$4 returning *",[typeof b.enabled==="boolean"?b.enabled:null,b.settings??null,companyId,b.module_key]);json(res,200,{ok:true,data:rows[0]});return true;
  }
  if(resource==="dashboard"&&req.method==="GET"){const[c,q,o,i]=await Promise.all([query<{count:string}>("select count(*)::text count from petra.customers where company_id=$1",[companyId]),query<{count:string}>("select count(*)::text count from petra.quotes where company_id=$1 and status not in ('approved','refused','expired')",[companyId]),query<{count:string}>("select count(*)::text count from petra.orders where company_id=$1 and status not in ('finished','cancelled')",[companyId]),query<{count:string}>("select count(*)::text count from petra.installations where company_id=$1 and status='scheduled'",[companyId])]);json(res,200,{ok:true,data:{customers:Number(c[0]?.count??0),openQuotes:Number(q[0]?.count??0),activeOrders:Number(o[0]?.count??0),plannedInstallations:Number(i[0]?.count??0)}});return true;}
  if(resource==="clients"&&!id&&req.method==="GET"){json(res,200,{ok:true,data:await query("select id,name,document_number,email,phone,whatsapp,address,notes,created_at,updated_at from petra.customers where company_id=$1 order by created_at desc",[companyId])});return true;}
  if(resource==="clients"&&!id&&req.method==="POST"){role(req,["admin","commercial"]);const b=await body(req);if(typeof b.name!=="string"||!b.name.trim()){json(res,400,{ok:false,error:{code:"NAME_REQUIRED",message:"Nome do cliente é obrigatório."}});return true;}const rows=await query("insert into petra.customers(company_id,name,document_number,email,phone,whatsapp,address,notes) values($1,$2,$3,$4,$5,$6,$7,$8) returning *",[companyId,b.name.trim(),b.document_number??null,b.email??null,b.phone??null,b.whatsapp??null,b.address??{},b.notes??null]);json(res,201,{ok:true,data:rows[0]});return true;}
  if(resource==="quotes"&&!id&&req.method==="GET"){json(res,200,{ok:true,data:await query("select q.*,c.name customer_name from petra.quotes q join petra.customers c on c.id=q.customer_id and c.company_id=q.company_id where q.company_id=$1 order by q.created_at desc",[companyId])});return true;}
  if(resource==="quotes"&&!id&&req.method==="POST"){role(req,["admin","commercial"]);const b=await body(req);if(typeof b.customer_id!=="string"||typeof b.number!=="string"){json(res,400,{ok:false,error:{code:"QUOTE_FIELDS_REQUIRED",message:"customer_id e number são obrigatórios."}});return true;}const customer=await query("select id from petra.customers where id=$1 and company_id=$2",[b.customer_id,companyId]);if(!customer.length){json(res,404,{ok:false,error:{code:"CUSTOMER_NOT_FOUND",message:"Cliente não encontrado nesta empresa."}});return true;}const rows=await query("insert into petra.quotes(company_id,customer_id,work_id,number,status,valid_until,subtotal,discount,total,payment_terms,notes) values($1,$2,$3,$4,'draft',$5,$6,$7,$8,$9,$10) returning *",[companyId,b.customer_id,b.work_id??null,b.number,b.valid_until??null,Number(b.subtotal??0),Number(b.discount??0),Number(b.total??0),b.payment_terms??null,b.notes??null]);const quoteId=(rows[0] as any).id;const items=Array.isArray(b.items)?b.items:[];for(const item of items){await query("insert into petra.quote_items(company_id,quote_id,environment_id,description,material,quantity,unit,unit_price,finish_charge,total,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",[companyId,quoteId,item.environment_id??null,String(item.description??"Item"),item.material??null,Number(item.quantity??1),item.unit??"un",Number(item.unit_price??0),Number(item.finish_charge??0),Number(item.total??0),item.metadata??{}]);}json(res,201,{ok:true,data:rows[0]});return true;}
  if(resource==="quotes"&&id&&parts[2]==="items"&&req.method==="GET"){json(res,200,{ok:true,data:await query("select * from petra.quote_items where company_id=$1 and quote_id=$2 order by id",[companyId,id])});return true;}
  if(resource==="quotes"&&id&&parts[2]==="approve"&&req.method==="POST"){role(req,["admin","commercial"]);const rows=await query("update petra.quotes set status='approved',approved_at=now() where id=$1 and company_id=$2 and status<>'approved' returning *",[id,companyId]);if(!rows.length){json(res,404,{ok:false,error:{code:"QUOTE_NOT_FOUND_OR_APPROVED",message:"Orçamento não encontrado ou já aprovado."}});return true;}await processOrderCreationJobs(companyId);const order=await query("select * from petra.orders where company_id=$1 and quote_id=$2 limit 1",[companyId,id]);json(res,200,{ok:true,data:{quote:rows[0],order:order[0]??null}});return true;}
  if(resource==="quotes"&&id&&req.method==="GET"){const rows=await query("select q.*,c.name customer_name from petra.quotes q join petra.customers c on c.id=q.customer_id where q.id=$1 and q.company_id=$2",[id,companyId]);if(!rows.length){json(res,404,{ok:false,error:{code:"QUOTE_NOT_FOUND",message:"Orçamento não encontrado."}});return true;}json(res,200,{ok:true,data:{...rows[0] as object,items:await query("select * from petra.quote_items where quote_id=$1 and company_id=$2",[id,companyId])}});return true;}
  if(resource==="orders"&&!id&&req.method==="GET"){json(res,200,{ok:true,data:await query("select o.*,c.name customer_name from petra.orders o join petra.customers c on c.id=o.customer_id and c.company_id=o.company_id where o.company_id=$1 order by o.created_at desc",[companyId])});return true;}
  if(resource==="orders"&&!id&&req.method==="POST"){role(req,["admin","commercial"]);const b=await body(req);if(typeof b.customer_id!=="string"||typeof b.number!=="string"||!b.number.trim()){json(res,400,{ok:false,error:{code:"ORDER_FIELDS_REQUIRED",message:"customer_id e number são obrigatórios."}});return true;}const customer=await query<{id:string}>("select id from petra.customers where id=$1 and company_id=$2",[b.customer_id,companyId]);if(!customer.length){json(res,404,{ok:false,error:{code:"CUSTOMER_NOT_FOUND",message:"Cliente não encontrado nesta empresa."}});return true;}const rows=await query("insert into petra.orders(company_id,customer_id,work_id,quote_id,number,status,payment_terms,total,notes) values($1,$2,$3,$4,$5,'new',$6,$7,$8) returning *",[companyId,b.customer_id,b.work_id??null,b.quote_id??null,b.number.trim(),b.payment_terms??null,Number(b.total??0),b.notes??null]);json(res,201,{ok:true,data:rows[0]});return true;}
  if(resource==="orders"&&id&&parts[2]==="measurements"&&req.method==="POST"){role(req,["admin","technical"]);const b=await body(req);if(!b.measured_at){json(res,400,{ok:false,error:{code:"MEASURED_AT_REQUIRED",message:"A data da medição é obrigatória."}});return true;}const order=await query("select id from petra.orders where id=$1 and company_id=$2",[id,companyId]);if(!order.length){json(res,404,{ok:false,error:{code:"ORDER_NOT_FOUND",message:"Pedido não encontrado."}});return true;}const rows=await query("insert into petra.measurements(company_id,order_id,environment_id,measured_at,status,checklist,evidence,notes) values($1,$2,$3,$4,$5,$6,$7,$8) returning *",[companyId,id,b.environment_id??null,b.measured_at,b.status??"draft",b.checklist??{},b.evidence??[],b.notes??null]);json(res,201,{ok:true,data:rows[0]});return true;}
  if(resource==="orders"&&id&&parts[2]==="production-release"&&req.method==="POST"){role(req,["admin","technical","production"]);const b=await body(req);if(typeof b.measurement_id!=="string"){json(res,400,{ok:false,error:{code:"MEASUREMENT_REQUIRED",message:"measurement_id é obrigatório."}});return true;}const valid=await query("select id from petra.measurements where id=$1 and order_id=$2 and company_id=$3 and status='approved' and measured_at is not null",[b.measurement_id,id,companyId]);if(!valid.length){json(res,409,{ok:false,error:{code:"MEASUREMENT_NOT_APPROVED",message:"A produção só pode ser liberada após medição aprovada com data."}});return true;}const rows=await query("insert into petra.production_releases(id,company_id,order_id,measurement_id,notes) values($1,$2,$3,$4,$5) returning *",[randomUUID(),companyId,id,b.measurement_id,b.notes??null]);await query("update petra.orders set production_released_at=now(),production_released_by=null,status='production' where id=$1 and company_id=$2",[id,companyId]);json(res,201,{ok:true,data:rows[0]});return true;}
  if(resource==="orders"&&id&&parts[2]==="status"&&req.method==="PATCH"){role(req,["admin","commercial","technical","production","installation"]);const b=await body(req);if(typeof b.status!=="string"){json(res,400,{ok:false,error:{code:"STATUS_REQUIRED",message:"status é obrigatório."}});return true;}const rows=await query("update petra.orders set status=$1 where id=$2 and company_id=$3 returning *",[b.status,id,companyId]);if(!rows.length){json(res,404,{ok:false,error:{code:"ORDER_NOT_FOUND",message:"Pedido não encontrado ou alteração bloqueada."}});return true;}json(res,200,{ok:true,data:rows[0]});return true;}
  if(resource==="orders"&&id&&req.method==="GET"){const rows=await query("select o.*,c.name customer_name from petra.orders o join petra.customers c on c.id=o.customer_id where o.id=$1 and o.company_id=$2",[id,companyId]);if(!rows.length){json(res,404,{ok:false,error:{code:"ORDER_NOT_FOUND",message:"Pedido não encontrado."}});return true;}const measurements=await query("select * from petra.measurements where order_id=$1 and company_id=$2 order by measured_at desc",[id,companyId]);const release=await query("select * from petra.production_releases where order_id=$1 and company_id=$2",[id,companyId]);json(res,200,{ok:true,data:{...rows[0] as object,measurements,productionRelease:release[0]??null}});return true;}
  if(resource==="documents"&&!id&&req.method==="GET"){json(res,200,{ok:true,data:await query("select * from petra.documents where company_id=$1 order by created_at desc",[companyId])});return true;}
  if(resource==="documents"&&!id&&req.method==="POST"){role(req,["admin","commercial","technical","production","installation"]);const b=await body(req);if(typeof b.title!=="string"||typeof b.document_type!=="string"){json(res,400,{ok:false,error:{code:"DOCUMENT_FIELDS_REQUIRED",message:"title e document_type são obrigatórios."}});return true;}const rows=await query("insert into petra.documents(company_id,customer_id,work_id,quote_id,order_id,environment_id,document_type,title,version,file_url,storage_provider,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,1,$9,$10,$11) returning *",[companyId,b.customer_id??null,b.work_id??null,b.quote_id??null,b.order_id??null,b.environment_id??null,b.document_type,b.title,b.file_url??null,b.storage_provider??null,b.metadata??{}]);json(res,201,{ok:true,data:rows[0]});return true;}
  if(resource==="automations"&&parts[1]==="run"&&req.method==="POST"){role(req,["admin"]);await processOrderCreationJobs(companyId);const pending=await query("select id,event_type,target,status,attempts,run_at,last_error from petra.automation_jobs where company_id=$1 order by created_at desc limit 100",[companyId]);json(res,200,{ok:true,data:pending});return true;}
  json(res,404,{ok:false,error:{code:"NOT_FOUND",message:"Endpoint não encontrado."}});return true;
 }catch(error){const e=error as Error&{status?:number;code?:string};json(res,e.status??500,{ok:false,error:{code:e.code??"INTERNAL_ERROR",message:e.message}});return true;}
}
